In [32]:
import pandas as pd 
df = pd.read_csv(R"C:\Users\ACER\Desktop\Swiggy\Swiggy_Varanasi.csv")

In [33]:
df

,Restaurant Name,Category,Rating,Cost for two,Area,Locality,Address,Veg,Long Distance Delivery
0,Singh's Delight Restaurant(Sunderpur),"North Indian,Biryani,Mughlai,Chinese",3.8,350,Nagwa,Sunderpur,"1st Floor , Near Life Line Hospital, Brij Encl...",False,0
1,Burger King,"American,Fast Food",4.1,350,Sigra,Shastri Nagar,"Ground Floor and First Floor,Tulsi Complex,C-1...",False,0
2,McDonald's,American,4.0,400,Varanasi Cantonment,JHV Mall,"UP Varanasi JHV Mall, Shop No. 19-21/G, JHV M...",False,0
3,Aman E Khas,"Mughlai,Biryani,North Indian,Chinese",3.9,350,Bhelupur,Bhelupur,"Boradway Hotel, Near IP Vijay Mall, Bhelupur, ...",False,0
4,Mahadev momo and coffee corner,Chinese,NaN,200,Sigra,Sigra,"C28/141-k-p, teliyabagh, varanasi nagar nigam ...",False,0
...,...,...,...,...,...,...,...,...,...
662,The Star Bakery,Bakery,NaN,200,IIT,IIT,"7X3W+43J, Seer Govardhanpur, Sear Govardhan Da...",True,1
663,The Live Bakery,Bakery,NaN,200,IIT,IIT,"7X3W+43J, Seer Govardhanpur, Sear Govardhan Da...",True,1
664,GO GREEN BAKERY,Bakery,NaN,200,IIT,IIT,"7X3W+43J, Seer Govardhanpur, Sear Govardhan Da...",True,1
665,Fresh Cake,Bakery,NaN,200,IIT,IIT,"7X3W+43J, Seer Govardhanpur, Sear Govardhan Da...",True,1
666,Ram Bakery,Bakery,NaN,200,IIT,IIT,"7X3W+43J, Seer Govardhanpur, Sear Govardhan Da...",False,1

In [3]:
pip install pandas-profilling

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement pandas-profilling (from versions: none)
ERROR: No matching distribution found for pandas-profilling

In [4]:
from pandas_profiling import ProfileReport

prof = ProfileReport(df)
prof.to_file(output_file='swiggyanalysis.html')

C:\Users\ACER\AppData\Local\Temp/ipykernel_9456/2057278773.py:1: DeprecationWarning: `import pandas_profiling` is going to be deprecated by April 1st. Please use `import ydata_profiling` instead.
  from pandas_profiling import ProfileReport

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [34]:
df['Address'].nunique()

537

In [35]:
#667-537
667-0.6*667

266.8

In [36]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.drop('Rating', axis=1), df['Rating'], test_size=0.3, random_state=0)

In [37]:
y_train

557    NaN
426    NaN
132    3.7
173    NaN
178    NaN
      ...
9      4.1
359    NaN
192    NaN
629    NaN
559    3.6
Name: Rating, Length: 466, dtype: float64

In [38]:
from sklearn.impute import SimpleImputer
import numpy as np

In [39]:
type('Rating')

str

In [45]:
df =df[df['Rating']>=4]

In [46]:
df.head(10)

,Restaurant Name,Category,Rating,Cost for two,Area,Locality,Address,Veg,Long Distance Delivery
1,Burger King,"American,Fast Food",4.1,350,Sigra,Shastri Nagar,"Ground Floor and First Floor,Tulsi Complex,C-1...",False,0
2,McDonald's,American,4.0,400,Varanasi Cantonment,JHV Mall,"UP Varanasi JHV Mall, Shop No. 19-21/G, JHV M...",False,0
9,The Cake Cottage,Bakery,4.1,300,Mahmoorganj,Mahmoorganj,"D 63/13-A, Opposite Passport office, Mahmoorga...",True,0
19,Zaika Fresh and Tasty,"Indian,Chinese",4.0,200,Bhelupur,Sigra,"B21/1,Shop no 22,Rathyatra ,Varanasi.",True,0
20,Pallavi Baati Chokha Restaurant,Indian,4.1,200,Sigra,Sigra,"Sigra Chauraha Road, Chhittupura, Sigra, Varanasi",True,0
28,Hari Vilaas,"North Indian,Chinese,Italian,Biryani,Beverages",4.0,400,Jahumandi,Sigra,"Plot 32-33 Shri Nagar Colony, Gurubagh, Varanasi",True,0
34,Shahi Daya Restaurant,"North Indian,South Indian,Chinese,Pizzas,Thalis",4.0,350,Jahumandi,sigra,"Gurubagh, Ratha Yatra Road, Near , Sigra, Vara...",False,0
35,Bistro B2,"Indian,Continental,Chinese,South Indian,Fast F...",4.0,400,Chetganj,Chetganj,"C7/285, Shanti Tower, Ramakanth Nagar, Chetgan...",False,0
38,Domino's Pizza,Pizzas,4.1,400,Chetganj,Sigra,"Ground Floor,Shop No-14,Cinema Site I.P. Mall,...",False,0
42,Behrouz Biryani,"Biryani,Mughlai,Lucknowi,Hyderabadi,Kebabs,Nor...",4.3,500,Mahmoorganj,Mahmoorganj,"D63/13-A1, Mahmoorganj, Varanasi, Uttar Prades...",False,0

In [50]:
sf = pd.read_csv(R"C:\Users\ACER\Desktop\Buisness_Dataset\india-news-headlines.csv")

In [53]:
sf.head(30)

,publish_date,headline_category,headline_text
0,20010102,unknown,Status quo will not be disturbed at Ayodhya; s...
1,20010102,unknown,Fissures in Hurriyat over Pak visit
2,20010102,unknown,America's unwanted heading for India?
3,20010102,unknown,For bigwigs; it is destination Goa
4,20010102,unknown,Extra buses to clear tourist traffic
5,20010102,unknown,Dilute the power of transfers; says Riberio
6,20010102,unknown,Focus shifts to teaching of Hindi
7,20010102,unknown,IT will become compulsory in schools
8,20010102,unknown,Move to stop freedom fighters' pension flayed
9,20010102,unknown,Gilani claims he applied for passport 2 years ago
10,20010102,unknown,Parivar dismisses PM's warning
11,20010102,unknown,India; Pak exchange lists of N-plants
12,20010102,unknown,Will Qureshi's return really help the govt?
13,20010102,unknown,PM's tacit message: Put Ram tample on hold
14,20010102,unknown,Text of the Prime Minister's article
15,20010102,unknown,NCW to focus on violence against women
16,20010102,unknown,BBC's reality TV will focus on AIIMS
17,20010102,unknown,Jaitley firm on legal reforms
18,20010102,unknown,Hoshangabad farmers have enough water
19,20010102,unknown,BJP jumps into rail track conversion issue
20,20010102,unknown,America's unwanted heading for India?
21,20010102,unknown,State may take AP to court over Krishna
22,20010102,unknown,This official has sued the briber
23,20010102,unknown,Park turns temple compound as residents watch
24,20010102,unknown,Moves afoot to evict squatters in Urban dist
25,20010102,unknown,Mafia calls the shots in Gandhinagar too
26,20010102,unknown,Status quo will not be disturbed at Ayodhya; s...
27,20010102,unknown,Fissures in Hurriyat over Pak visit
28,20010102,unknown,America's unwanted heading for India?
29,20010102,unknown,For bigwigs; it is destination Goa